server:
  port: 8080
spring:
  application:
    name: SpringBootJpa
  profiles:
    active: test
  messages:
    basename:
      core/messages_zh_CN.properties,core/messages_en_EN.properties
  jpa:
      database: MYSQL
      show-sql: true
      format_sql: true
      hibernate:
        ddl-auto: none
        naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect