server:
  port: 8080
  servlet:
    context-path : /mykbp
spring:
  application:
    name: SpringBootJpa
  profiles:
    active: test
  aop:
     proxy-target-class: false
  cache:
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
      config: classpath:ehcache/ehcache.xml
  session:
    store-type: redis
  messages:
    basename:
      core/messages.properties,core/messages_zh_CN.properties
  devtools:
    restart:
      enabled: false
  jpa:
      database: MYSQL
      show-sql: true
      format_sql: true
      hibernate:
        ddl-auto: none
        naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate5:
    packages: com.cn.springbootjpa
    properties:
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 1000
    password: Pass1234 
    pool: 
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    provider: org.springframework.data.redis.cache.RedisCacheManager
    time-to-live: 60000
logging:
  file: /app/logs/${spring.application.name}.log
  level:
    root: INFO
    path: E:/log/springbootjpa