server:
  port: 8080
spring:
  application:
    name: SpringBootJpa
  profiles:
    active: test
  jpa:
      database: MYSQL
      show-sql: true
      format_sql: true
      hibernate:
        ddl-auto: update
        naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
        dialect: org.hibernate.dialect.MySQL57Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        database-platform: org.hibernate.dialect.MySQL57Dialect#设置创建表的引擎为InnoDB