server:
  port: 8080
  servlet:
    context-path : /api
spring:
  application:
    name: SpringBootJpa
  profiles:
    active: localhost
  aop:
     proxy-target-class: false
  jackson:
    serialization.INDENT_OUTPUT: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  session:
    store-type: redis
  cache:
    type: jcache
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
      config: classpath:ehcache/ehcache.xml
  data:
    redis:
      repositories:
        enabled: false
  messages:
    basename:
      i18n/messages.properties,i18n/messages_zh_CN.properties
  devtools:
    restart:
      enabled: false
  jpa:
      database: MYSQL
      show-sql: true
      format_sql: true
      open-in-view: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: none
        naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      properties:
        hibernate:
          cache:
            use_second_level_cache: true
            use_query_cache: true
            region:
              factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
            javax:
              cache:
                provider: org.ehcache.jsr107.EhcacheCachingProvider  
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1000
    password: Pass1234 
    pool: 
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
      
security:
  jwt:
    login: /api/login
    logout: /api/logout
    refresh: refresh
    prefix: Bearer
    header: Authorization
    expiration: 86400
    secret: changeitasyouwish
    
logging:
  file: /app/logs/${spring.application.name}.log
  level:
    root: INFO