package com.cn.springbootjpa.system.entity;

// Generated 2008-6-18 15:50:09 by Hibernate Tools 3.2.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.cn.springbootjpa.base.entity.BaseEntity;

/**
 * TiIfsMqsInMsg generated by hbm2java
 */
@Entity
@Table(name = "TI_IFS_MQS_IN_MSG")
public class TiIfsMqsInMsg extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3058663124745765928L;

	public static final String PO_TIIFSMQSINMSG = "TiIfsMqsInMsg";

	public static final String FIELD_TIIFSCONFIG = "tiIfsConfig";

	public static final String FIELD_ID = "id";

	public static final String FIELD_TIIFSCONFIGID = "tiIfsConfigId";

	public static final String FIELD_MESSAGETYPE = "messageType";

	public static final String FIELD_MESSAGEFORMAT = "messageFormat";

	public static final String FIELD_SEQUENCEID = "sequenceId";

	public static final String FIELD_RECEIVEMSG = "receiveMsg";

	public static final String FIELD_RECEIVETIME = "receiveTime";

	public static final String FIELD_RECEIVEOK = "receiveOk";

	public static final String FIELD_RETURNMSG = "returnMsg";

	public static final String FIELD_MESSAGEID = "messageId";

	public static final String FIELD_CORRELATIONID = "correlationId";

	public static final String FIELD_OPERATORID = "operatorId";

	public static final String FIELD_OPERATORNAME = "operatorName";

	public static final String FIELD_REMOTEMACADDR = "remoteMacAddr";

	private TiIfsConfig tiIfsConfig;

	private Integer id;

	private Integer tiIfsConfigId;

	private String messageType;

	private String messageFormat;

	private Integer sequenceId;

	private String receiveMsg;

	private Date receiveTime;

	private Boolean receiveOk;

	private String returnMsg;

	private String messageId;

	private String correlationId;

	private String operatorId;

	private String operatorName;

	private String remoteMacAddr;

	public TiIfsMqsInMsg() {
	}

	public TiIfsMqsInMsg(TiIfsConfig tiIfsConfig, Integer id) {
		this.tiIfsConfig = tiIfsConfig;
		this.id = id;
	}

	public TiIfsMqsInMsg(TiIfsConfig tiIfsConfig, Integer id, String messageType,
			String messageFormat, Integer sequenceId, String receiveMsg,
			Date receiveTime, Boolean receiveOk, String returnMsg,
			String messageId, String correlationId, String operatorId,
			String operatorName, String remoteMacAddr) {
		this.tiIfsConfig = tiIfsConfig;
		this.id = id;
		this.messageType = messageType;
		this.messageFormat = messageFormat;
		this.sequenceId = sequenceId;
		this.receiveMsg = receiveMsg;
		this.receiveTime = receiveTime;
		this.receiveOk = receiveOk;
		this.returnMsg = returnMsg;
		this.messageId = messageId;
		this.correlationId = correlationId;
		this.operatorId = operatorId;
		this.operatorName = operatorName;
		this.remoteMacAddr = remoteMacAddr;
	}

	@SequenceGenerator(name = "generator", sequenceName = "TI_IFS_MQS_IN_MSG_SEQ1", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "TI_IFS_MQS_IN_MSG_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TI_IFS_CONFIG_ID")
	public TiIfsConfig getTiIfsConfig() {
		return this.tiIfsConfig;
	}

	public void setTiIfsConfig(TiIfsConfig tiIfsConfig) {
		this.tiIfsConfig = tiIfsConfig;
	}

	@Column(name = "MESSAGE_TYPE", length = 30)
	public String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	@Column(name = "MESSAGE_FORMAT", length = 2)
	public String getMessageFormat() {
		return this.messageFormat;
	}

	public void setMessageFormat(String messageFormat) {
		this.messageFormat = messageFormat;
	}

	@Column(name = "SEQUENCE_ID", precision = 10, scale = 0)
	public Integer getSequenceId() {
		return this.sequenceId;
	}

	public void setSequenceId(Integer sequenceId) {
		this.sequenceId = sequenceId;
	}

	@Column(name = "RECEIVE_MSG", length = 256)
	public String getReceiveMsg() {
		return this.receiveMsg;
	}

	public void setReceiveMsg(String receiveMsg) {
		this.receiveMsg = receiveMsg;
	}

	@Column(name = "RECEIVE_TIME", length = 11)
	public Date getReceiveTime() {
		return this.receiveTime;
	}

	public void setReceiveTime(Date receiveTime) {
		this.receiveTime = receiveTime;
	}

	@Column(name = "RECEIVE_OK", length = 1)
	public Boolean getReceiveOk() {
		return this.receiveOk;
	}

	public void setReceiveOk(Boolean receiveOk) {
		this.receiveOk = receiveOk;
	}

	@Column(name = "RETURN_MSG", length = 512)
	public String getReturnMsg() {
		return this.returnMsg;
	}

	public void setReturnMsg(String returnMsg) {
		this.returnMsg = returnMsg;
	}

	@Column(name = "MESSAGE_ID", length = 60)
	public String getMessageId() {
		return this.messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	@Column(name = "CORRELATION_ID", length = 60)
	public String getCorrelationId() {
		return this.correlationId;
	}

	public void setCorrelationId(String correlationId) {
		this.correlationId = correlationId;
	}

	@Column(name = "OPERATOR_ID", length = 20)
	public String getOperatorId() {
		return operatorId;
	}

	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	@Column(name = "OPERATOR_NAME", length = 30)
	public String getOperatorName() {
		return operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	@Column(name = "REMOTE_MAC_ADDR", length = 40)
	public String getRemoteMacAddr() {
		return remoteMacAddr;
	}

	public void setRemoteMacAddr(String remoteMacAddr) {
		this.remoteMacAddr = remoteMacAddr;
	}

	@Column(name = "TI_IFS_CONFIG_ID", insertable = false, updatable = false)
	public Integer getTiIfsConfigId() {
		return tiIfsConfigId;
	}

	public void setTiIfsConfigId(Integer tiIfsConfigId) {
		this.tiIfsConfigId = tiIfsConfigId;
	}
}
