package com.cn.springbootjpa.mq.msgentity;

// Generated 2008-6-18 15:50:09 by Hibernate Tools 3.2.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.cn.springbootjpa.base.entity.BaseEntity;

/**
 * TiIfsMqsOutMsg generated by hbm2java
 */
@Entity
@Table(name = "TI_IFS_MQS_OUT_MSG")
public class TiIfsMqsOutMsg extends BaseEntity {


	/**
	 * 
	 */
	private static final long serialVersionUID = -6655214625053645998L;

	public static final String PO_TIIFSMQSOUTMSG = "TiIfsMqsOutMsg";

	public static final String FIELD_ID = "id";

	public static final String FIELD_TIIFSCONFIGID = "tiIfsConfigId";

	public static final String FIELD_TIIFSCONFIG = "tiIfsConfig";

	public static final String FIELD_MESSAGETYPE = "messageType";

	public static final String FIELD_MESSAGEFORMAT = "messageFormat";

	public static final String FIELD_SEQUENCEID = "sequenceId";

	public static final String FIELD_SENDMSG = "sendMsg";

	public static final String FIELD_SENDTIME = "sendTime";

	public static final String FIELD_SENDOK = "sendOk";

	public static final String FIELD_RETURNMSG = "returnMsg";

	public static final String FIELD_MESSAGEID = "messageId";

	public static final String FIELD_CORRELATIONID = "correlationId";

	public static final String FIELD_RESENDCOUNTER = "resendCounter";

	public static final String FIELD_NEEDRESEND = "needResend";

	public static final String FIELD_OPERATORID = "operatorId";

	public static final String FIELD_OPERATORNAME = "operatorName";

	public static final String FIELD_REMOTEMACADDR = "remoteMacAddr";

	public static final String FIELD_ALERT_SENT = "alertSent";
	
	public static final String FIELD_MSGHEADER = "msgHeader";

	private Integer id;

	private Integer tiIfsConfigId;

	private TiIfsConfig tiIfsConfig;

	private String messageType;

	private String messageFormat;

	private Integer sequenceId;

	private String sendMsg;

	private Date sendTime;

	private Boolean sendOk;

	private String returnMsg;

	private String messageId;

	private String correlationId;

	private Integer resendCounter;

	private Boolean needResend;

	private String operatorId;

	private String operatorName;

	private String remoteMacAddr;

	private Character alertSent;

	/**
	 * @Fields msgHeader : 消息头（多个子系统通过此消息头区分）
	 */
	private String msgHeader;
	
	public TiIfsMqsOutMsg() {
	}

	public TiIfsMqsOutMsg(TiIfsConfig tiIfsConfig, String messageType,
			String messageFormat, Integer sequenceId, String sendMsg,
			Date sendTime, Boolean sendOk, String returnMsg, String messageId,
			String correlationId, Integer resendCounter, Boolean needResend,
			String operatorId, String operatorName, String remoteMacAddr,
			Character alertSent) {
		this.tiIfsConfig = tiIfsConfig;
		this.messageType = messageType;
		this.messageFormat = messageFormat;
		this.sequenceId = sequenceId;
		this.sendMsg = sendMsg;
		this.sendTime = sendTime;
		this.sendOk = sendOk;
		this.returnMsg = returnMsg;
		this.messageId = messageId;
		this.correlationId = correlationId;
		this.resendCounter = resendCounter;
		this.needResend = needResend;
		this.operatorId = operatorId;
		this.operatorName = operatorName;
		this.remoteMacAddr = remoteMacAddr;
		this.alertSent = alertSent;
	}

	@SequenceGenerator(name = "generator", sequenceName = "TI_IFS_MQS_OUT_MSG_SEQ1", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "TI_IFS_MQS_OUT_MSG_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TI_IFS_CONFIG_ID")
	public TiIfsConfig getTiIfsConfig() {
		return this.tiIfsConfig;
	}

	public void setTiIfsConfig(TiIfsConfig tiIfsConfig) {
		this.tiIfsConfig = tiIfsConfig;
	}

	@Column(name = "MESSAGE_TYPE", length = 30)
	public String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	@Column(name = "MESSAGE_FORMAT", length = 2)
	public String getMessageFormat() {
		return this.messageFormat;
	}

	public void setMessageFormat(String messageFormat) {
		this.messageFormat = messageFormat;
	}

	@Column(name = "SEQUENCE_ID", precision = 10, scale = 0)
	public Integer getSequenceId() {
		return this.sequenceId;
	}

	public void setSequenceId(Integer sequenceId) {
		this.sequenceId = sequenceId;
	}

	@Column(name = "SEND_MSG", length = 256)
	public String getSendMsg() {
		return this.sendMsg;
	}

	public void setSendMsg(String sendMsg) {
		this.sendMsg = sendMsg;
	}

	@Column(name = "SEND_TIME", length = 11)
	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	@Column(name = "SEND_OK", length = 1)
	public Boolean getSendOk() {
		return this.sendOk;
	}

	public void setSendOk(Boolean sendOk) {
		this.sendOk = sendOk;
	}

	@Column(name = "RETURN_MSG", length = 128)
	public String getReturnMsg() {
		return this.returnMsg;
	}

	public void setReturnMsg(String returnMsg) {
		this.returnMsg = returnMsg;
	}

	@Column(name = "MESSAGE_ID", length = 60)
	public String getMessageId() {
		return this.messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	@Column(name = "CORRELATION_ID", length = 60)
	public String getCorrelationId() {
		return this.correlationId;
	}

	public void setCorrelationId(String correlationId) {
		this.correlationId = correlationId;
	}

	@Column(name = "RESEND_COUNTER", precision = 10, scale = 0)
	public Integer getResendCounter() {
		return this.resendCounter;
	}

	public void setResendCounter(Integer resendCounter) {
		this.resendCounter = resendCounter;
	}

	@Column(name = "NEED_RESEND", length = 1)
	public Boolean getNeedResend() {
		return this.needResend;
	}

	public void setNeedResend(Boolean needResend) {
		this.needResend = needResend;
	}

	@Column(name = "OPERATOR_ID", length = 20)
	public String getOperatorId() {
		return operatorId;
	}

	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	@Column(name = "OPERATOR_NAME", length = 30)
	public String getOperatorName() {
		return operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	@Column(name = "REMOTE_MAC_ADDR", length = 40)
	public String getRemoteMacAddr() {
		return remoteMacAddr;
	}

	public void setRemoteMacAddr(String remoteMacAddr) {
		this.remoteMacAddr = remoteMacAddr;
	}

	@Column(name = "ALERT_SENT", length = 1)
	public Character getAlertSent() {
		return alertSent;
	}

	public void setAlertSent(Character alertSent) {
		this.alertSent = alertSent;
	}

	@Column(name = "TI_IFS_CONFIG_ID", insertable = false, updatable = false)
	public Integer getTiIfsConfigId() {
		return tiIfsConfigId;
	}

	public void setTiIfsConfigId(Integer tiIfsConfigId) {
		this.tiIfsConfigId = tiIfsConfigId;
	}

	@Column(name = "MSG_HEADER", length = 50)
	public String getMsgHeader() {
		return msgHeader;
	}

	public void setMsgHeader(String msgHeader) {
		this.msgHeader = msgHeader;
	}

	
}
